var filenames=[
"Spain.sst.jpg",
"Spain.sstanomaly.jpg",
"Spain.arrows.6.gif",
"Spain.pressure.6.gif",
"Spain.pressure_arrows.6.gif",
"Spain.fl.metric.6.gif",
"Spain.fl.imperial.6.gif",
"Spain.htsgw.metric.6.jpg",
"Spain.htsgw.imperial.6.jpg",
"Spain.peak_wave_period.6.jpg",
"Spain.swell1energy.6.jpg",
"Spain.swell2energy.6.jpg",
"Spain.wwvenergy.6.jpg",
"Spain.maxenergy.6.jpg",
"Spain.cloud.6.jpg",
"Spain.lapse.6.jpg",
"Spain.wind.6.jpg",
"Spain.prec.6.jpg",
"Spain.arrows.12.gif",
"Spain.pressure.12.gif",
"Spain.pressure_arrows.12.gif",
"Spain.fl.metric.12.gif",
"Spain.fl.imperial.12.gif",
"Spain.htsgw.metric.12.jpg",
"Spain.htsgw.imperial.12.jpg",
"Spain.peak_wave_period.12.jpg",
"Spain.swell1energy.12.jpg",
"Spain.swell2energy.12.jpg",
"Spain.wwvenergy.12.jpg",
"Spain.maxenergy.12.jpg",
"Spain.cloud.12.jpg",
"Spain.lapse.12.jpg",
"Spain.wind.12.jpg",
"Spain.prec.12.jpg",
"Spain.arrows.18.gif",
"Spain.pressure.18.gif",
"Spain.pressure_arrows.18.gif",
"Spain.fl.metric.18.gif",
"Spain.fl.imperial.18.gif",
"Spain.htsgw.metric.18.jpg",
"Spain.htsgw.imperial.18.jpg",
"Spain.peak_wave_period.18.jpg",
"Spain.swell1energy.18.jpg",
"Spain.swell2energy.18.jpg",
"Spain.wwvenergy.18.jpg",
"Spain.maxenergy.18.jpg",
"Spain.cloud.18.jpg",
"Spain.lapse.18.jpg",
"Spain.wind.18.jpg",
"Spain.prec.18.jpg",
"Spain.arrows.24.gif",
"Spain.pressure.24.gif",
"Spain.pressure_arrows.24.gif",
"Spain.fl.metric.24.gif",
"Spain.fl.imperial.24.gif",
"Spain.htsgw.metric.24.jpg",
"Spain.htsgw.imperial.24.jpg",
"Spain.peak_wave_period.24.jpg",
"Spain.swell1energy.24.jpg",
"Spain.swell2energy.24.jpg",
"Spain.wwvenergy.24.jpg",
"Spain.maxenergy.24.jpg",
"Spain.cloud.24.jpg",
"Spain.lapse.24.jpg",
"Spain.wind.24.jpg",
"Spain.prec.24.jpg",
"Spain.arrows.30.gif",
"Spain.pressure.30.gif",
"Spain.pressure_arrows.30.gif",
"Spain.fl.metric.30.gif",
"Spain.fl.imperial.30.gif",
"Spain.htsgw.metric.30.jpg",
"Spain.htsgw.imperial.30.jpg",
"Spain.peak_wave_period.30.jpg",
"Spain.swell1energy.30.jpg",
"Spain.swell2energy.30.jpg",
"Spain.wwvenergy.30.jpg",
"Spain.maxenergy.30.jpg",
"Spain.cloud.30.jpg",
"Spain.lapse.30.jpg",
"Spain.wind.30.jpg",
"Spain.prec.30.jpg",
"Spain.arrows.36.gif",
"Spain.pressure.36.gif",
"Spain.pressure_arrows.36.gif",
"Spain.fl.metric.36.gif",
"Spain.fl.imperial.36.gif",
"Spain.htsgw.metric.36.jpg",
"Spain.htsgw.imperial.36.jpg",
"Spain.peak_wave_period.36.jpg",
"Spain.swell1energy.36.jpg",
"Spain.swell2energy.36.jpg",
"Spain.wwvenergy.36.jpg",
"Spain.maxenergy.36.jpg",
"Spain.cloud.36.jpg",
"Spain.lapse.36.jpg",
"Spain.wind.36.jpg",
"Spain.prec.36.jpg",
"Spain.arrows.42.gif",
"Spain.pressure.42.gif",
"Spain.pressure_arrows.42.gif",
"Spain.fl.metric.42.gif",
"Spain.fl.imperial.42.gif",
"Spain.htsgw.metric.42.jpg",
"Spain.htsgw.imperial.42.jpg",
"Spain.peak_wave_period.42.jpg",
"Spain.swell1energy.42.jpg",
"Spain.swell2energy.42.jpg",
"Spain.wwvenergy.42.jpg",
"Spain.maxenergy.42.jpg",
"Spain.cloud.42.jpg",
"Spain.lapse.42.jpg",
"Spain.wind.42.jpg",
"Spain.prec.42.jpg",
"Spain.arrows.48.gif",
"Spain.pressure.48.gif",
"Spain.pressure_arrows.48.gif",
"Spain.fl.metric.48.gif",
"Spain.fl.imperial.48.gif",
"Spain.htsgw.metric.48.jpg",
"Spain.htsgw.imperial.48.jpg",
"Spain.peak_wave_period.48.jpg",
"Spain.swell1energy.48.jpg",
"Spain.swell2energy.48.jpg",
"Spain.wwvenergy.48.jpg",
"Spain.maxenergy.48.jpg",
"Spain.cloud.48.jpg",
"Spain.lapse.48.jpg",
"Spain.wind.48.jpg",
"Spain.prec.48.jpg",
"Spain.arrows.54.gif",
"Spain.pressure.54.gif",
"Spain.pressure_arrows.54.gif",
"Spain.fl.metric.54.gif",
"Spain.fl.imperial.54.gif",
"Spain.htsgw.metric.54.jpg",
"Spain.htsgw.imperial.54.jpg",
"Spain.peak_wave_period.54.jpg",
"Spain.swell1energy.54.jpg",
"Spain.swell2energy.54.jpg",
"Spain.wwvenergy.54.jpg",
"Spain.maxenergy.54.jpg",
"Spain.cloud.54.jpg",
"Spain.lapse.54.jpg",
"Spain.wind.54.jpg",
"Spain.prec.54.jpg",
"Spain.arrows.60.gif",
"Spain.pressure.60.gif",
"Spain.pressure_arrows.60.gif",
"Spain.fl.metric.60.gif",
"Spain.fl.imperial.60.gif",
"Spain.htsgw.metric.60.jpg",
"Spain.htsgw.imperial.60.jpg",
"Spain.peak_wave_period.60.jpg",
"Spain.swell1energy.60.jpg",
"Spain.swell2energy.60.jpg",
"Spain.wwvenergy.60.jpg",
"Spain.maxenergy.60.jpg",
"Spain.cloud.60.jpg",
"Spain.lapse.60.jpg",
"Spain.wind.60.jpg",
"Spain.prec.60.jpg",
"Spain.arrows.66.gif",
"Spain.pressure.66.gif",
"Spain.pressure_arrows.66.gif",
"Spain.fl.metric.66.gif",
"Spain.fl.imperial.66.gif",
"Spain.htsgw.metric.66.jpg",
"Spain.htsgw.imperial.66.jpg",
"Spain.peak_wave_period.66.jpg",
"Spain.swell1energy.66.jpg",
"Spain.swell2energy.66.jpg",
"Spain.wwvenergy.66.jpg",
"Spain.maxenergy.66.jpg",
"Spain.cloud.66.jpg",
"Spain.lapse.66.jpg",
"Spain.wind.66.jpg",
"Spain.prec.66.jpg",
"Spain.arrows.72.gif",
"Spain.pressure.72.gif",
"Spain.pressure_arrows.72.gif",
"Spain.fl.metric.72.gif",
"Spain.fl.imperial.72.gif",
"Spain.htsgw.metric.72.jpg",
"Spain.htsgw.imperial.72.jpg",
"Spain.peak_wave_period.72.jpg",
"Spain.swell1energy.72.jpg",
"Spain.swell2energy.72.jpg",
"Spain.wwvenergy.72.jpg",
"Spain.maxenergy.72.jpg",
"Spain.cloud.72.jpg",
"Spain.lapse.72.jpg",
"Spain.wind.72.jpg",
"Spain.prec.72.jpg",
"Spain.arrows.78.gif",
"Spain.pressure.78.gif",
"Spain.pressure_arrows.78.gif",
"Spain.fl.metric.78.gif",
"Spain.fl.imperial.78.gif",
"Spain.htsgw.metric.78.jpg",
"Spain.htsgw.imperial.78.jpg",
"Spain.peak_wave_period.78.jpg",
"Spain.swell1energy.78.jpg",
"Spain.swell2energy.78.jpg",
"Spain.wwvenergy.78.jpg",
"Spain.maxenergy.78.jpg",
"Spain.cloud.78.jpg",
"Spain.lapse.78.jpg",
"Spain.wind.78.jpg",
"Spain.prec.78.jpg",
"Spain.arrows.84.gif",
"Spain.pressure.84.gif",
"Spain.pressure_arrows.84.gif",
"Spain.fl.metric.84.gif",
"Spain.fl.imperial.84.gif",
"Spain.htsgw.metric.84.jpg",
"Spain.htsgw.imperial.84.jpg",
"Spain.peak_wave_period.84.jpg",
"Spain.swell1energy.84.jpg",
"Spain.swell2energy.84.jpg",
"Spain.wwvenergy.84.jpg",
"Spain.maxenergy.84.jpg",
"Spain.cloud.84.jpg",
"Spain.lapse.84.jpg",
"Spain.wind.84.jpg",
"Spain.prec.84.jpg",
"Spain.arrows.90.gif",
"Spain.pressure.90.gif",
"Spain.pressure_arrows.90.gif",
"Spain.fl.metric.90.gif",
"Spain.fl.imperial.90.gif",
"Spain.htsgw.metric.90.jpg",
"Spain.htsgw.imperial.90.jpg",
"Spain.peak_wave_period.90.jpg",
"Spain.swell1energy.90.jpg",
"Spain.swell2energy.90.jpg",
"Spain.wwvenergy.90.jpg",
"Spain.maxenergy.90.jpg",
"Spain.cloud.90.jpg",
"Spain.lapse.90.jpg",
"Spain.wind.90.jpg",
"Spain.prec.90.jpg",
"Spain.arrows.96.gif",
"Spain.pressure.96.gif",
"Spain.pressure_arrows.96.gif",
"Spain.fl.metric.96.gif",
"Spain.fl.imperial.96.gif",
"Spain.htsgw.metric.96.jpg",
"Spain.htsgw.imperial.96.jpg",
"Spain.peak_wave_period.96.jpg",
"Spain.swell1energy.96.jpg",
"Spain.swell2energy.96.jpg",
"Spain.wwvenergy.96.jpg",
"Spain.maxenergy.96.jpg",
"Spain.cloud.96.jpg",
"Spain.lapse.96.jpg",
"Spain.wind.96.jpg",
"Spain.prec.96.jpg",
"Spain.arrows.102.gif",
"Spain.pressure.102.gif",
"Spain.pressure_arrows.102.gif",
"Spain.fl.metric.102.gif",
"Spain.fl.imperial.102.gif",
"Spain.htsgw.metric.102.jpg",
"Spain.htsgw.imperial.102.jpg",
"Spain.peak_wave_period.102.jpg",
"Spain.swell1energy.102.jpg",
"Spain.swell2energy.102.jpg",
"Spain.wwvenergy.102.jpg",
"Spain.maxenergy.102.jpg",
"Spain.cloud.102.jpg",
"Spain.lapse.102.jpg",
"Spain.wind.102.jpg",
"Spain.prec.102.jpg",
"Spain.arrows.108.gif",
"Spain.pressure.108.gif",
"Spain.pressure_arrows.108.gif",
"Spain.fl.metric.108.gif",
"Spain.fl.imperial.108.gif",
"Spain.htsgw.metric.108.jpg",
"Spain.htsgw.imperial.108.jpg",
"Spain.peak_wave_period.108.jpg",
"Spain.swell1energy.108.jpg",
"Spain.swell2energy.108.jpg",
"Spain.wwvenergy.108.jpg",
"Spain.maxenergy.108.jpg",
"Spain.cloud.108.jpg",
"Spain.lapse.108.jpg",
"Spain.wind.108.jpg",
"Spain.prec.108.jpg",
"Spain.arrows.114.gif",
"Spain.pressure.114.gif",
"Spain.pressure_arrows.114.gif",
"Spain.fl.metric.114.gif",
"Spain.fl.imperial.114.gif",
"Spain.htsgw.metric.114.jpg",
"Spain.htsgw.imperial.114.jpg",
"Spain.peak_wave_period.114.jpg",
"Spain.swell1energy.114.jpg",
"Spain.swell2energy.114.jpg",
"Spain.wwvenergy.114.jpg",
"Spain.maxenergy.114.jpg",
"Spain.cloud.114.jpg",
"Spain.lapse.114.jpg",
"Spain.wind.114.jpg",
"Spain.prec.114.jpg",
"Spain.arrows.120.gif",
"Spain.pressure.120.gif",
"Spain.pressure_arrows.120.gif",
"Spain.fl.metric.120.gif",
"Spain.fl.imperial.120.gif",
"Spain.htsgw.metric.120.jpg",
"Spain.htsgw.imperial.120.jpg",
"Spain.peak_wave_period.120.jpg",
"Spain.swell1energy.120.jpg",
"Spain.swell2energy.120.jpg",
"Spain.wwvenergy.120.jpg",
"Spain.maxenergy.120.jpg",
"Spain.cloud.120.jpg",
"Spain.lapse.120.jpg",
"Spain.wind.120.jpg",
"Spain.prec.120.jpg",
"Spain.arrows.126.gif",
"Spain.pressure.126.gif",
"Spain.pressure_arrows.126.gif",
"Spain.fl.metric.126.gif",
"Spain.fl.imperial.126.gif",
"Spain.htsgw.metric.126.jpg",
"Spain.htsgw.imperial.126.jpg",
"Spain.peak_wave_period.126.jpg",
"Spain.swell1energy.126.jpg",
"Spain.swell2energy.126.jpg",
"Spain.wwvenergy.126.jpg",
"Spain.maxenergy.126.jpg",
"Spain.cloud.126.jpg",
"Spain.lapse.126.jpg",
"Spain.wind.126.jpg",
"Spain.prec.126.jpg",
"Spain.arrows.132.gif",
"Spain.pressure.132.gif",
"Spain.pressure_arrows.132.gif",
"Spain.fl.metric.132.gif",
"Spain.fl.imperial.132.gif",
"Spain.htsgw.metric.132.jpg",
"Spain.htsgw.imperial.132.jpg",
"Spain.peak_wave_period.132.jpg",
"Spain.swell1energy.132.jpg",
"Spain.swell2energy.132.jpg",
"Spain.wwvenergy.132.jpg",
"Spain.maxenergy.132.jpg",
"Spain.cloud.132.jpg",
"Spain.lapse.132.jpg",
"Spain.wind.132.jpg",
"Spain.prec.132.jpg",
"Spain.arrows.138.gif",
"Spain.pressure.138.gif",
"Spain.pressure_arrows.138.gif",
"Spain.fl.metric.138.gif",
"Spain.fl.imperial.138.gif",
"Spain.htsgw.metric.138.jpg",
"Spain.htsgw.imperial.138.jpg",
"Spain.peak_wave_period.138.jpg",
"Spain.swell1energy.138.jpg",
"Spain.swell2energy.138.jpg",
"Spain.wwvenergy.138.jpg",
"Spain.maxenergy.138.jpg",
"Spain.cloud.138.jpg",
"Spain.lapse.138.jpg",
"Spain.wind.138.jpg",
"Spain.prec.138.jpg",
"Spain.arrows.144.gif",
"Spain.pressure.144.gif",
"Spain.pressure_arrows.144.gif",
"Spain.fl.metric.144.gif",
"Spain.fl.imperial.144.gif",
"Spain.htsgw.metric.144.jpg",
"Spain.htsgw.imperial.144.jpg",
"Spain.peak_wave_period.144.jpg",
"Spain.swell1energy.144.jpg",
"Spain.swell2energy.144.jpg",
"Spain.wwvenergy.144.jpg",
"Spain.maxenergy.144.jpg",
"Spain.cloud.144.jpg",
"Spain.lapse.144.jpg",
"Spain.wind.144.jpg",
"Spain.prec.144.jpg",
"Spain.arrows.150.gif",
"Spain.pressure.150.gif",
"Spain.pressure_arrows.150.gif",
"Spain.fl.metric.150.gif",
"Spain.fl.imperial.150.gif",
"Spain.htsgw.metric.150.jpg",
"Spain.htsgw.imperial.150.jpg",
"Spain.peak_wave_period.150.jpg",
"Spain.swell1energy.150.jpg",
"Spain.swell2energy.150.jpg",
"Spain.wwvenergy.150.jpg",
"Spain.maxenergy.150.jpg",
"Spain.cloud.150.jpg",
"Spain.lapse.150.jpg",
"Spain.wind.150.jpg",
"Spain.prec.150.jpg",
"Spain.arrows.156.gif",
"Spain.pressure.156.gif",
"Spain.pressure_arrows.156.gif",
"Spain.fl.metric.156.gif",
"Spain.fl.imperial.156.gif",
"Spain.htsgw.metric.156.jpg",
"Spain.htsgw.imperial.156.jpg",
"Spain.peak_wave_period.156.jpg",
"Spain.swell1energy.156.jpg",
"Spain.swell2energy.156.jpg",
"Spain.wwvenergy.156.jpg",
"Spain.maxenergy.156.jpg",
"Spain.cloud.156.jpg",
"Spain.lapse.156.jpg",
"Spain.wind.156.jpg",
"Spain.prec.156.jpg",
"Spain.arrows.162.gif",
"Spain.pressure.162.gif",
"Spain.pressure_arrows.162.gif",
"Spain.fl.metric.162.gif",
"Spain.fl.imperial.162.gif",
"Spain.htsgw.metric.162.jpg",
"Spain.htsgw.imperial.162.jpg",
"Spain.peak_wave_period.162.jpg",
"Spain.swell1energy.162.jpg",
"Spain.swell2energy.162.jpg",
"Spain.wwvenergy.162.jpg",
"Spain.maxenergy.162.jpg",
"Spain.cloud.162.jpg",
"Spain.lapse.162.jpg",
"Spain.wind.162.jpg",
"Spain.prec.162.jpg",
"Spain.arrows.168.gif",
"Spain.pressure.168.gif",
"Spain.pressure_arrows.168.gif",
"Spain.fl.metric.168.gif",
"Spain.fl.imperial.168.gif",
"Spain.htsgw.metric.168.jpg",
"Spain.htsgw.imperial.168.jpg",
"Spain.peak_wave_period.168.jpg",
"Spain.swell1energy.168.jpg",
"Spain.swell2energy.168.jpg",
"Spain.wwvenergy.168.jpg",
"Spain.maxenergy.168.jpg",
"Spain.cloud.168.jpg",
"Spain.lapse.168.jpg",
"Spain.wind.168.jpg",
"Spain.prec.168.jpg",
"Spain.arrows.174.gif",
"Spain.pressure.174.gif",
"Spain.pressure_arrows.174.gif",
"Spain.fl.metric.174.gif",
"Spain.fl.imperial.174.gif",
"Spain.htsgw.metric.174.jpg",
"Spain.htsgw.imperial.174.jpg",
"Spain.peak_wave_period.174.jpg",
"Spain.swell1energy.174.jpg",
"Spain.swell2energy.174.jpg",
"Spain.wwvenergy.174.jpg",
"Spain.maxenergy.174.jpg",
"Spain.cloud.174.jpg",
"Spain.lapse.174.jpg",
"Spain.wind.174.jpg",
"Spain.prec.174.jpg",
"Spain.arrows.180.gif",
"Spain.pressure.180.gif",
"Spain.pressure_arrows.180.gif",
"Spain.fl.metric.180.gif",
"Spain.fl.imperial.180.gif",
"Spain.htsgw.metric.180.jpg",
"Spain.htsgw.imperial.180.jpg",
"Spain.peak_wave_period.180.jpg",
"Spain.swell1energy.180.jpg",
"Spain.swell2energy.180.jpg",
"Spain.wwvenergy.180.jpg",
"Spain.maxenergy.180.jpg",
"Spain.cloud.180.jpg",
"Spain.lapse.180.jpg",
"Spain.wind.180.jpg",
"Spain.prec.180.jpg",
"Spain.arrows.186.gif",
"Spain.pressure.186.gif",
"Spain.pressure_arrows.186.gif",
"Spain.fl.metric.186.gif",
"Spain.fl.imperial.186.gif",
"Spain.cloud.186.jpg",
"Spain.lapse.186.jpg",
"Spain.wind.186.jpg",
"Spain.prec.186.jpg",
"Spain.arrows.192.gif",
"Spain.pressure.192.gif",
"Spain.pressure_arrows.192.gif",
"Spain.fl.metric.192.gif",
"Spain.fl.imperial.192.gif",
"Spain.cloud.192.jpg",
"Spain.lapse.192.jpg",
"Spain.wind.192.jpg",
"Spain.prec.192.jpg",
"Spain.arrows.198.gif",
"Spain.pressure.198.gif",
"Spain.pressure_arrows.198.gif",
"Spain.fl.metric.198.gif",
"Spain.fl.imperial.198.gif",
"Spain.cloud.198.jpg",
"Spain.lapse.198.jpg",
"Spain.wind.198.jpg",
"Spain.prec.198.jpg",
"Spain.arrows.204.gif",
"Spain.pressure.204.gif",
"Spain.pressure_arrows.204.gif",
"Spain.fl.metric.204.gif",
"Spain.fl.imperial.204.gif",
"Spain.cloud.204.jpg",
"Spain.lapse.204.jpg",
"Spain.wind.204.jpg",
"Spain.prec.204.jpg",
"Spain.arrows.210.gif",
"Spain.pressure.210.gif",
"Spain.pressure_arrows.210.gif",
"Spain.fl.metric.210.gif",
"Spain.fl.imperial.210.gif",
"Spain.cloud.210.jpg",
"Spain.lapse.210.jpg",
"Spain.wind.210.jpg",
"Spain.prec.210.jpg",
"Spain.arrows.216.gif",
"Spain.pressure.216.gif",
"Spain.pressure_arrows.216.gif",
"Spain.fl.metric.216.gif",
"Spain.fl.imperial.216.gif",
"Spain.cloud.216.jpg",
"Spain.lapse.216.jpg",
"Spain.wind.216.jpg",
"Spain.prec.216.jpg",
"Spain.arrows.222.gif",
"Spain.pressure.222.gif",
"Spain.pressure_arrows.222.gif",
"Spain.fl.metric.222.gif",
"Spain.fl.imperial.222.gif",
"Spain.cloud.222.jpg",
"Spain.lapse.222.jpg",
"Spain.wind.222.jpg",
"Spain.prec.222.jpg",
"Spain.arrows.228.gif",
"Spain.pressure.228.gif",
"Spain.pressure_arrows.228.gif",
"Spain.fl.metric.228.gif",
"Spain.fl.imperial.228.gif",
"Spain.cloud.228.jpg",
"Spain.lapse.228.jpg",
"Spain.wind.228.jpg",
"Spain.prec.228.jpg",
"Spain.arrows.234.gif",
"Spain.pressure.234.gif",
"Spain.pressure_arrows.234.gif",
"Spain.fl.metric.234.gif",
"Spain.fl.imperial.234.gif",
"Spain.cloud.234.jpg",
"Spain.lapse.234.jpg",
"Spain.wind.234.jpg",
"Spain.prec.234.jpg",
"Spain.arrows.240.gif",
"Spain.pressure.240.gif",
"Spain.pressure_arrows.240.gif",
"Spain.fl.metric.240.gif",
"Spain.fl.imperial.240.gif",
"Spain.cloud.240.jpg",
"Spain.lapse.240.jpg",
"Spain.wind.240.jpg",
"Spain.prec.240.jpg",
"Spain.arrows.246.gif",
"Spain.pressure.246.gif",
"Spain.pressure_arrows.246.gif",
"Spain.fl.metric.246.gif",
"Spain.fl.imperial.246.gif",
"Spain.cloud.246.jpg",
"Spain.lapse.246.jpg",
"Spain.wind.246.jpg",
"Spain.prec.246.jpg",
"Spain.arrows.252.gif",
"Spain.pressure.252.gif",
"Spain.pressure_arrows.252.gif",
"Spain.fl.metric.252.gif",
"Spain.fl.imperial.252.gif",
"Spain.cloud.252.jpg",
"Spain.lapse.252.jpg",
"Spain.wind.252.jpg",
"Spain.prec.252.jpg",
"Spain.arrows.258.gif",
"Spain.pressure.258.gif",
"Spain.pressure_arrows.258.gif",
"Spain.fl.metric.258.gif",
"Spain.fl.imperial.258.gif",
"Spain.cloud.258.jpg",
"Spain.lapse.258.jpg",
"Spain.wind.258.jpg",
"Spain.prec.258.jpg",
"Spain.arrows.264.gif",
"Spain.pressure.264.gif",
"Spain.pressure_arrows.264.gif",
"Spain.fl.metric.264.gif",
"Spain.fl.imperial.264.gif",
"Spain.cloud.264.jpg",
"Spain.lapse.264.jpg",
"Spain.wind.264.jpg",
"Spain.prec.264.jpg",
"Spain.arrows.270.gif",
"Spain.pressure.270.gif",
"Spain.pressure_arrows.270.gif",
"Spain.fl.metric.270.gif",
"Spain.fl.imperial.270.gif",
"Spain.cloud.270.jpg",
"Spain.lapse.270.jpg",
"Spain.wind.270.jpg",
"Spain.prec.270.jpg",
"Spain.arrows.276.gif",
"Spain.pressure.276.gif",
"Spain.pressure_arrows.276.gif",
"Spain.fl.metric.276.gif",
"Spain.fl.imperial.276.gif",
"Spain.cloud.276.jpg",
"Spain.lapse.276.jpg",
"Spain.wind.276.jpg",
"Spain.prec.276.jpg",
"Spain.arrows.282.gif",
"Spain.pressure.282.gif",
"Spain.pressure_arrows.282.gif",
"Spain.fl.metric.282.gif",
"Spain.fl.imperial.282.gif",
"Spain.cloud.282.jpg",
"Spain.lapse.282.jpg",
"Spain.wind.282.jpg",
"Spain.prec.282.jpg",
"Spain.arrows.288.gif",
"Spain.pressure.288.gif",
"Spain.pressure_arrows.288.gif",
"Spain.fl.metric.288.gif",
"Spain.fl.imperial.288.gif",
"Spain.cloud.288.jpg",
"Spain.lapse.288.jpg",
"Spain.wind.288.jpg",
"Spain.prec.288.jpg",
"Spain.arrows.294.gif",
"Spain.pressure.294.gif",
"Spain.pressure_arrows.294.gif",
"Spain.fl.metric.294.gif",
"Spain.fl.imperial.294.gif",
"Spain.cloud.294.jpg",
"Spain.lapse.294.jpg",
"Spain.wind.294.jpg",
"Spain.prec.294.jpg",
"Spain.arrows.300.gif",
"Spain.pressure.300.gif",
"Spain.pressure_arrows.300.gif",
"Spain.fl.metric.300.gif",
"Spain.fl.imperial.300.gif",
"Spain.cloud.300.jpg",
"Spain.lapse.300.jpg",
"Spain.wind.300.jpg",
"Spain.prec.300.jpg"
];
var titles=[
"Current Sea Surface Temperatures in degs C",
"Sea Surface Temperatures Anomaly in degs C",
"Arrows show the wind direction Monday 12 Oct at 8pm",
"Sea Level Pressure in Millibars Monday 12 Oct at 8pm",
"Lines show pressure and arrows show wind direction Monday 12 Oct at 8pm",
"FREEZING LEVEL CONTOURED (RED) IN METRES Monday 12 Oct at 8pm",
"FREEZING LEVEL CONTOURED (RED) IN FEET Monday 12 Oct at 8pm",
"Significant Wave Height in metres on Monday 12 Oct at 8pm CEST",
"Significant Wave Height in feet on Monday 12 Oct at 8pm CEST",
"Peak wave period on Monday 12 Oct at 8pm CEST",
"Primary Swell energy on Monday 12 Oct at 8pm CEST",
"Secondary Swell energy on Monday 12 Oct at 8pm CEST",
"Wind Wave energy on Monday 12 Oct at 8pm CEST",
"Max Wave energy on Monday 12 Oct at 8pm CEST",
"Cloud Cover on Monday 12 Oct at 8pm CEST",
"Surface Temperature on Monday 12 Oct at 8pm CEST",
"Surface Wind on Monday 12 Oct at 8pm CEST",
"Precipitation for 3 hrs ending Monday 12 Oct at 8pm CEST",
"Freezing level contours Tuesday 13 Oct at 2am",
"Sea Level Pressure in Millibars Tuesday 13 Oct at 2am",
"Lines show pressure and arrows show wind direction Tuesday 13 Oct at 2am",
"FREEZING LEVEL CONTOURED (RED) IN METRES Tuesday 13 Oct at 2am",
"FREEZING LEVEL CONTOURED (RED) IN FEET Tuesday 13 Oct at 2am",
"Significant Wave Height in metres on Tuesday 13 Oct at 2am CEST",
"Significant Wave Height in feet on Tuesday 13 Oct at 2am CEST",
"Peak wave period on Tuesday 13 Oct at 2am CEST",
"Primary Swell energy on Tuesday 13 Oct at 2am CEST",
"Secondary Swell energy on Tuesday 13 Oct at 2am CEST",
"Wind Wave energy on Tuesday 13 Oct at 2am CEST",
"Max Wave energy on Tuesday 13 Oct at 2am CEST",
"Cloud Cover on Tuesday 13 Oct at 2am CEST",
"Surface Temperature on Tuesday 13 Oct at 2am CEST",
"Surface Wind on Tuesday 13 Oct at 2am CEST",
"Precipitation for 3 hrs ending Tuesday 13 Oct at 2am CEST",
"Freezing level contours Tuesday 13 Oct at 8am",
"Sea Level Pressure in Millibars Tuesday 13 Oct at 8am",
"Lines show pressure and arrows show wind direction Tuesday 13 Oct at 8am",
"FREEZING LEVEL CONTOURED (RED) IN METRES Tuesday 13 Oct at 8am",
"FREEZING LEVEL CONTOURED (RED) IN FEET Tuesday 13 Oct at 8am",
"Significant Wave Height in metres on Tuesday 13 Oct at 8am CEST",
"Significant Wave Height in feet on Tuesday 13 Oct at 8am CEST",
"Peak wave period on Tuesday 13 Oct at 8am CEST",
"Primary Swell energy on Tuesday 13 Oct at 8am CEST",
"Secondary Swell energy on Tuesday 13 Oct at 8am CEST",
"Wind Wave energy on Tuesday 13 Oct at 8am CEST",
"Max Wave energy on Tuesday 13 Oct at 8am CEST",
"Cloud Cover on Tuesday 13 Oct at 8am CEST",
"Surface Temperature on Tuesday 13 Oct at 8am CEST",
"Surface Wind on Tuesday 13 Oct at 8am CEST",
"Precipitation for 3 hrs ending Tuesday 13 Oct at 8am CEST",
"Freezing level contours Tuesday 13 Oct at 2pm",
"Sea Level Pressure in Millibars Tuesday 13 Oct at 2pm",
"Lines show pressure and arrows show wind direction Tuesday 13 Oct at 2pm",
"FREEZING LEVEL CONTOURED (RED) IN METRES Tuesday 13 Oct at 2pm",
"FREEZING LEVEL CONTOURED (RED) IN FEET Tuesday 13 Oct at 2pm",
"Significant Wave Height in metres on Tuesday 13 Oct at 2pm CEST",
"Significant Wave Height in feet on Tuesday 13 Oct at 2pm CEST",
"Peak wave period on Tuesday 13 Oct at 2pm CEST",
"Primary Swell energy on Tuesday 13 Oct at 2pm CEST",
"Secondary Swell energy on Tuesday 13 Oct at 2pm CEST",
"Wind Wave energy on Tuesday 13 Oct at 2pm CEST",
"Max Wave energy on Tuesday 13 Oct at 2pm CEST",
"Cloud Cover on Tuesday 13 Oct at 2pm CEST",
"Surface Temperature on Tuesday 13 Oct at 2pm CEST",
"Surface Wind on Tuesday 13 Oct at 2pm CEST",
"Precipitation for 3 hrs ending Tuesday 13 Oct at 2pm CEST",
"Freezing level contours Tuesday 13 Oct at 8pm",
"Sea Level Pressure in Millibars Tuesday 13 Oct at 8pm",
"Lines show pressure and arrows show wind direction Tuesday 13 Oct at 8pm",
"FREEZING LEVEL CONTOURED (RED) IN METRES Tuesday 13 Oct at 8pm",
"FREEZING LEVEL CONTOURED (RED) IN FEET Tuesday 13 Oct at 8pm",
"Significant Wave Height in metres on Tuesday 13 Oct at 8pm CEST",
"Significant Wave Height in feet on Tuesday 13 Oct at 8pm CEST",
"Peak wave period on Tuesday 13 Oct at 8pm CEST",
"Primary Swell energy on Tuesday 13 Oct at 8pm CEST",
"Secondary Swell energy on Tuesday 13 Oct at 8pm CEST",
"Wind Wave energy on Tuesday 13 Oct at 8pm CEST",
"Max Wave energy on Tuesday 13 Oct at 8pm CEST",
"Cloud Cover on Tuesday 13 Oct at 8pm CEST",
"Surface Temperature on Tuesday 13 Oct at 8pm CEST",
"Surface Wind on Tuesday 13 Oct at 8pm CEST",
"Precipitation for 3 hrs ending Tuesday 13 Oct at 8pm CEST",
"Freezing level contours Wednesday 14 Oct at 2am",
"Sea Level Pressure in Millibars Wednesday 14 Oct at 2am",
"Lines show pressure and arrows show wind direction Wednesday 14 Oct at 2am",
"FREEZING LEVEL CONTOURED (RED) IN METRES Wednesday 14 Oct at 2am",
"FREEZING LEVEL CONTOURED (RED) IN FEET Wednesday 14 Oct at 2am",
"Significant Wave Height in metres on Wednesday 14 Oct at 2am CEST",
"Significant Wave Height in feet on Wednesday 14 Oct at 2am CEST",
"Peak wave period on Wednesday 14 Oct at 2am CEST",
"Primary Swell energy on Wednesday 14 Oct at 2am CEST",
"Secondary Swell energy on Wednesday 14 Oct at 2am CEST",
"Wind Wave energy on Wednesday 14 Oct at 2am CEST",
"Max Wave energy on Wednesday 14 Oct at 2am CEST",
"Cloud Cover on Wednesday 14 Oct at 2am CEST",
"Surface Temperature on Wednesday 14 Oct at 2am CEST",
"Surface Wind on Wednesday 14 Oct at 2am CEST",
"Precipitation for 3 hrs ending Wednesday 14 Oct at 2am CEST",
"Freezing level contours Wednesday 14 Oct at 8am",
"Sea Level Pressure in Millibars Wednesday 14 Oct at 8am",
"Lines show pressure and arrows show wind direction Wednesday 14 Oct at 8am",
"FREEZING LEVEL CONTOURED (RED) IN METRES Wednesday 14 Oct at 8am",
"FREEZING LEVEL CONTOURED (RED) IN FEET Wednesday 14 Oct at 8am",
"Significant Wave Height in metres on Wednesday 14 Oct at 8am CEST",
"Significant Wave Height in feet on Wednesday 14 Oct at 8am CEST",
"Peak wave period on Wednesday 14 Oct at 8am CEST",
"Primary Swell energy on Wednesday 14 Oct at 8am CEST",
"Secondary Swell energy on Wednesday 14 Oct at 8am CEST",
"Wind Wave energy on Wednesday 14 Oct at 8am CEST",
"Max Wave energy on Wednesday 14 Oct at 8am CEST",
"Cloud Cover on Wednesday 14 Oct at 8am CEST",
"Surface Temperature on Wednesday 14 Oct at 8am CEST",
"Surface Wind on Wednesday 14 Oct at 8am CEST",
"Precipitation for 3 hrs ending Wednesday 14 Oct at 8am CEST",
"Freezing level contours Wednesday 14 Oct at 2pm",
"Sea Level Pressure in Millibars Wednesday 14 Oct at 2pm",
"Lines show pressure and arrows show wind direction Wednesday 14 Oct at 2pm",
"FREEZING LEVEL CONTOURED (RED) IN METRES Wednesday 14 Oct at 2pm",
"FREEZING LEVEL CONTOURED (RED) IN FEET Wednesday 14 Oct at 2pm",
"Significant Wave Height in metres on Wednesday 14 Oct at 2pm CEST",
"Significant Wave Height in feet on Wednesday 14 Oct at 2pm CEST",
"Peak wave period on Wednesday 14 Oct at 2pm CEST",
"Primary Swell energy on Wednesday 14 Oct at 2pm CEST",
"Secondary Swell energy on Wednesday 14 Oct at 2pm CEST",
"Wind Wave energy on Wednesday 14 Oct at 2pm CEST",
"Max Wave energy on Wednesday 14 Oct at 2pm CEST",
"Cloud Cover on Wednesday 14 Oct at 2pm CEST",
"Surface Temperature on Wednesday 14 Oct at 2pm CEST",
"Surface Wind on Wednesday 14 Oct at 2pm CEST",
"Precipitation for 3 hrs ending Wednesday 14 Oct at 2pm CEST",
"Freezing level contours Wednesday 14 Oct at 8pm",
"Sea Level Pressure in Millibars Wednesday 14 Oct at 8pm",
"Lines show pressure and arrows show wind direction Wednesday 14 Oct at 8pm",
"FREEZING LEVEL CONTOURED (RED) IN METRES Wednesday 14 Oct at 8pm",
"FREEZING LEVEL CONTOURED (RED) IN FEET Wednesday 14 Oct at 8pm",
"Significant Wave Height in metres on Wednesday 14 Oct at 8pm CEST",
"Significant Wave Height in feet on Wednesday 14 Oct at 8pm CEST",
"Peak wave period on Wednesday 14 Oct at 8pm CEST",
"Primary Swell energy on Wednesday 14 Oct at 8pm CEST",
"Secondary Swell energy on Wednesday 14 Oct at 8pm CEST",
"Wind Wave energy on Wednesday 14 Oct at 8pm CEST",
"Max Wave energy on Wednesday 14 Oct at 8pm CEST",
"Cloud Cover on Wednesday 14 Oct at 8pm CEST",
"Surface Temperature on Wednesday 14 Oct at 8pm CEST",
"Surface Wind on Wednesday 14 Oct at 8pm CEST",
"Precipitation for 3 hrs ending Wednesday 14 Oct at 8pm CEST",
"Freezing level contours Thursday 15 Oct at 2am",
"Sea Level Pressure in Millibars Thursday 15 Oct at 2am",
"Lines show pressure and arrows show wind direction Thursday 15 Oct at 2am",
"FREEZING LEVEL CONTOURED (RED) IN METRES Thursday 15 Oct at 2am",
"FREEZING LEVEL CONTOURED (RED) IN FEET Thursday 15 Oct at 2am",
"Significant Wave Height in metres on Thursday 15 Oct at 2am CEST",
"Significant Wave Height in feet on Thursday 15 Oct at 2am CEST",
"Peak wave period on Thursday 15 Oct at 2am CEST",
"Primary Swell energy on Thursday 15 Oct at 2am CEST",
"Secondary Swell energy on Thursday 15 Oct at 2am CEST",
"Wind Wave energy on Thursday 15 Oct at 2am CEST",
"Max Wave energy on Thursday 15 Oct at 2am CEST",
"Cloud Cover on Thursday 15 Oct at 2am CEST",
"Surface Temperature on Thursday 15 Oct at 2am CEST",
"Surface Wind on Thursday 15 Oct at 2am CEST",
"Precipitation for 3 hrs ending Thursday 15 Oct at 2am CEST",
"Freezing level contours Thursday 15 Oct at 8am",
"Sea Level Pressure in Millibars Thursday 15 Oct at 8am",
"Lines show pressure and arrows show wind direction Thursday 15 Oct at 8am",
"FREEZING LEVEL CONTOURED (RED) IN METRES Thursday 15 Oct at 8am",
"FREEZING LEVEL CONTOURED (RED) IN FEET Thursday 15 Oct at 8am",
"Significant Wave Height in metres on Thursday 15 Oct at 8am CEST",
"Significant Wave Height in feet on Thursday 15 Oct at 8am CEST",
"Peak wave period on Thursday 15 Oct at 8am CEST",
"Primary Swell energy on Thursday 15 Oct at 8am CEST",
"Secondary Swell energy on Thursday 15 Oct at 8am CEST",
"Wind Wave energy on Thursday 15 Oct at 8am CEST",
"Max Wave energy on Thursday 15 Oct at 8am CEST",
"Cloud Cover on Thursday 15 Oct at 8am CEST",
"Surface Temperature on Thursday 15 Oct at 8am CEST",
"Surface Wind on Thursday 15 Oct at 8am CEST",
"Precipitation for 3 hrs ending Thursday 15 Oct at 8am CEST",
"Freezing level contours Thursday 15 Oct at 2pm",
"Sea Level Pressure in Millibars Thursday 15 Oct at 2pm",
"Lines show pressure and arrows show wind direction Thursday 15 Oct at 2pm",
"FREEZING LEVEL CONTOURED (RED) IN METRES Thursday 15 Oct at 2pm",
"FREEZING LEVEL CONTOURED (RED) IN FEET Thursday 15 Oct at 2pm",
"Significant Wave Height in metres on Thursday 15 Oct at 2pm CEST",
"Significant Wave Height in feet on Thursday 15 Oct at 2pm CEST",
"Peak wave period on Thursday 15 Oct at 2pm CEST",
"Primary Swell energy on Thursday 15 Oct at 2pm CEST",
"Secondary Swell energy on Thursday 15 Oct at 2pm CEST",
"Wind Wave energy on Thursday 15 Oct at 2pm CEST",
"Max Wave energy on Thursday 15 Oct at 2pm CEST",
"Cloud Cover on Thursday 15 Oct at 2pm CEST",
"Surface Temperature on Thursday 15 Oct at 2pm CEST",
"Surface Wind on Thursday 15 Oct at 2pm CEST",
"Precipitation for 3 hrs ending Thursday 15 Oct at 2pm CEST",
"Freezing level contours Thursday 15 Oct at 8pm",
"Sea Level Pressure in Millibars Thursday 15 Oct at 8pm",
"Lines show pressure and arrows show wind direction Thursday 15 Oct at 8pm",
"FREEZING LEVEL CONTOURED (RED) IN METRES Thursday 15 Oct at 8pm",
"FREEZING LEVEL CONTOURED (RED) IN FEET Thursday 15 Oct at 8pm",
"Significant Wave Height in metres on Thursday 15 Oct at 8pm CEST",
"Significant Wave Height in feet on Thursday 15 Oct at 8pm CEST",
"Peak wave period on Thursday 15 Oct at 8pm CEST",
"Primary Swell energy on Thursday 15 Oct at 8pm CEST",
"Secondary Swell energy on Thursday 15 Oct at 8pm CEST",
"Wind Wave energy on Thursday 15 Oct at 8pm CEST",
"Max Wave energy on Thursday 15 Oct at 8pm CEST",
"Cloud Cover on Thursday 15 Oct at 8pm CEST",
"Surface Temperature on Thursday 15 Oct at 8pm CEST",
"Surface Wind on Thursday 15 Oct at 8pm CEST",
"Precipitation for 3 hrs ending Thursday 15 Oct at 8pm CEST",
"Freezing level contours Friday 16 Oct at 2am",
"Sea Level Pressure in Millibars Friday 16 Oct at 2am",
"Lines show pressure and arrows show wind direction Friday 16 Oct at 2am",
"FREEZING LEVEL CONTOURED (RED) IN METRES Friday 16 Oct at 2am",
"FREEZING LEVEL CONTOURED (RED) IN FEET Friday 16 Oct at 2am",
"Significant Wave Height in metres on Friday 16 Oct at 2am CEST",
"Significant Wave Height in feet on Friday 16 Oct at 2am CEST",
"Peak wave period on Friday 16 Oct at 2am CEST",
"Primary Swell energy on Friday 16 Oct at 2am CEST",
"Secondary Swell energy on Friday 16 Oct at 2am CEST",
"Wind Wave energy on Friday 16 Oct at 2am CEST",
"Max Wave energy on Friday 16 Oct at 2am CEST",
"Cloud Cover on Friday 16 Oct at 2am CEST",
"Surface Temperature on Friday 16 Oct at 2am CEST",
"Surface Wind on Friday 16 Oct at 2am CEST",
"Precipitation for 3 hrs ending Friday 16 Oct at 2am CEST",
"Freezing level contours Friday 16 Oct at 8am",
"Sea Level Pressure in Millibars Friday 16 Oct at 8am",
"Lines show pressure and arrows show wind direction Friday 16 Oct at 8am",
"FREEZING LEVEL CONTOURED (RED) IN METRES Friday 16 Oct at 8am",
"FREEZING LEVEL CONTOURED (RED) IN FEET Friday 16 Oct at 8am",
"Significant Wave Height in metres on Friday 16 Oct at 8am CEST",
"Significant Wave Height in feet on Friday 16 Oct at 8am CEST",
"Peak wave period on Friday 16 Oct at 8am CEST",
"Primary Swell energy on Friday 16 Oct at 8am CEST",
"Secondary Swell energy on Friday 16 Oct at 8am CEST",
"Wind Wave energy on Friday 16 Oct at 8am CEST",
"Max Wave energy on Friday 16 Oct at 8am CEST",
"Cloud Cover on Friday 16 Oct at 8am CEST",
"Surface Temperature on Friday 16 Oct at 8am CEST",
"Surface Wind on Friday 16 Oct at 8am CEST",
"Precipitation for 3 hrs ending Friday 16 Oct at 8am CEST",
"Freezing level contours Friday 16 Oct at 2pm",
"Sea Level Pressure in Millibars Friday 16 Oct at 2pm",
"Lines show pressure and arrows show wind direction Friday 16 Oct at 2pm",
"FREEZING LEVEL CONTOURED (RED) IN METRES Friday 16 Oct at 2pm",
"FREEZING LEVEL CONTOURED (RED) IN FEET Friday 16 Oct at 2pm",
"Significant Wave Height in metres on Friday 16 Oct at 2pm CEST",
"Significant Wave Height in feet on Friday 16 Oct at 2pm CEST",
"Peak wave period on Friday 16 Oct at 2pm CEST",
"Primary Swell energy on Friday 16 Oct at 2pm CEST",
"Secondary Swell energy on Friday 16 Oct at 2pm CEST",
"Wind Wave energy on Friday 16 Oct at 2pm CEST",
"Max Wave energy on Friday 16 Oct at 2pm CEST",
"Cloud Cover on Friday 16 Oct at 2pm CEST",
"Surface Temperature on Friday 16 Oct at 2pm CEST",
"Surface Wind on Friday 16 Oct at 2pm CEST",
"Precipitation for 3 hrs ending Friday 16 Oct at 2pm CEST",
"Freezing level contours Friday 16 Oct at 8pm",
"Sea Level Pressure in Millibars Friday 16 Oct at 8pm",
"Lines show pressure and arrows show wind direction Friday 16 Oct at 8pm",
"FREEZING LEVEL CONTOURED (RED) IN METRES Friday 16 Oct at 8pm",
"FREEZING LEVEL CONTOURED (RED) IN FEET Friday 16 Oct at 8pm",
"Significant Wave Height in metres on Friday 16 Oct at 8pm CEST",
"Significant Wave Height in feet on Friday 16 Oct at 8pm CEST",
"Peak wave period on Friday 16 Oct at 8pm CEST",
"Primary Swell energy on Friday 16 Oct at 8pm CEST",
"Secondary Swell energy on Friday 16 Oct at 8pm CEST",
"Wind Wave energy on Friday 16 Oct at 8pm CEST",
"Max Wave energy on Friday 16 Oct at 8pm CEST",
"Cloud Cover on Friday 16 Oct at 8pm CEST",
"Surface Temperature on Friday 16 Oct at 8pm CEST",
"Surface Wind on Friday 16 Oct at 8pm CEST",
"Precipitation for 3 hrs ending Friday 16 Oct at 8pm CEST",
"Freezing level contours Saturday 17 Oct at 2am",
"Sea Level Pressure in Millibars Saturday 17 Oct at 2am",
"Lines show pressure and arrows show wind direction Saturday 17 Oct at 2am",
"FREEZING LEVEL CONTOURED (RED) IN METRES Saturday 17 Oct at 2am",
"FREEZING LEVEL CONTOURED (RED) IN FEET Saturday 17 Oct at 2am",
"Significant Wave Height in metres on Saturday 17 Oct at 2am CEST",
"Significant Wave Height in feet on Saturday 17 Oct at 2am CEST",
"Peak wave period on Saturday 17 Oct at 2am CEST",
"Primary Swell energy on Saturday 17 Oct at 2am CEST",
"Secondary Swell energy on Saturday 17 Oct at 2am CEST",
"Wind Wave energy on Saturday 17 Oct at 2am CEST",
"Max Wave energy on Saturday 17 Oct at 2am CEST",
"Cloud Cover on Saturday 17 Oct at 2am CEST",
"Surface Temperature on Saturday 17 Oct at 2am CEST",
"Surface Wind on Saturday 17 Oct at 2am CEST",
"Precipitation for 3 hrs ending Saturday 17 Oct at 2am CEST",
"Freezing level contours Saturday 17 Oct at 8am",
"Sea Level Pressure in Millibars Saturday 17 Oct at 8am",
"Lines show pressure and arrows show wind direction Saturday 17 Oct at 8am",
"FREEZING LEVEL CONTOURED (RED) IN METRES Saturday 17 Oct at 8am",
"FREEZING LEVEL CONTOURED (RED) IN FEET Saturday 17 Oct at 8am",
"Significant Wave Height in metres on Saturday 17 Oct at 8am CEST",
"Significant Wave Height in feet on Saturday 17 Oct at 8am CEST",
"Peak wave period on Saturday 17 Oct at 8am CEST",
"Primary Swell energy on Saturday 17 Oct at 8am CEST",
"Secondary Swell energy on Saturday 17 Oct at 8am CEST",
"Wind Wave energy on Saturday 17 Oct at 8am CEST",
"Max Wave energy on Saturday 17 Oct at 8am CEST",
"Cloud Cover on Saturday 17 Oct at 8am CEST",
"Surface Temperature on Saturday 17 Oct at 8am CEST",
"Surface Wind on Saturday 17 Oct at 8am CEST",
"Precipitation for 3 hrs ending Saturday 17 Oct at 8am CEST",
"Freezing level contours Saturday 17 Oct at 2pm",
"Sea Level Pressure in Millibars Saturday 17 Oct at 2pm",
"Lines show pressure and arrows show wind direction Saturday 17 Oct at 2pm",
"FREEZING LEVEL CONTOURED (RED) IN METRES Saturday 17 Oct at 2pm",
"FREEZING LEVEL CONTOURED (RED) IN FEET Saturday 17 Oct at 2pm",
"Significant Wave Height in metres on Saturday 17 Oct at 2pm CEST",
"Significant Wave Height in feet on Saturday 17 Oct at 2pm CEST",
"Peak wave period on Saturday 17 Oct at 2pm CEST",
"Primary Swell energy on Saturday 17 Oct at 2pm CEST",
"Secondary Swell energy on Saturday 17 Oct at 2pm CEST",
"Wind Wave energy on Saturday 17 Oct at 2pm CEST",
"Max Wave energy on Saturday 17 Oct at 2pm CEST",
"Cloud Cover on Saturday 17 Oct at 2pm CEST",
"Surface Temperature on Saturday 17 Oct at 2pm CEST",
"Surface Wind on Saturday 17 Oct at 2pm CEST",
"Precipitation for 3 hrs ending Saturday 17 Oct at 2pm CEST",
"Freezing level contours Saturday 17 Oct at 8pm",
"Sea Level Pressure in Millibars Saturday 17 Oct at 8pm",
"Lines show pressure and arrows show wind direction Saturday 17 Oct at 8pm",
"FREEZING LEVEL CONTOURED (RED) IN METRES Saturday 17 Oct at 8pm",
"FREEZING LEVEL CONTOURED (RED) IN FEET Saturday 17 Oct at 8pm",
"Significant Wave Height in metres on Saturday 17 Oct at 8pm CEST",
"Significant Wave Height in feet on Saturday 17 Oct at 8pm CEST",
"Peak wave period on Saturday 17 Oct at 8pm CEST",
"Primary Swell energy on Saturday 17 Oct at 8pm CEST",
"Secondary Swell energy on Saturday 17 Oct at 8pm CEST",
"Wind Wave energy on Saturday 17 Oct at 8pm CEST",
"Max Wave energy on Saturday 17 Oct at 8pm CEST",
"Cloud Cover on Saturday 17 Oct at 8pm CEST",
"Surface Temperature on Saturday 17 Oct at 8pm CEST",
"Surface Wind on Saturday 17 Oct at 8pm CEST",
"Precipitation for 3 hrs ending Saturday 17 Oct at 8pm CEST",
"Freezing level contours Sunday 18 Oct at 2am",
"Sea Level Pressure in Millibars Sunday 18 Oct at 2am",
"Lines show pressure and arrows show wind direction Sunday 18 Oct at 2am",
"FREEZING LEVEL CONTOURED (RED) IN METRES Sunday 18 Oct at 2am",
"FREEZING LEVEL CONTOURED (RED) IN FEET Sunday 18 Oct at 2am",
"Significant Wave Height in metres on Sunday 18 Oct at 2am CEST",
"Significant Wave Height in feet on Sunday 18 Oct at 2am CEST",
"Peak wave period on Sunday 18 Oct at 2am CEST",
"Primary Swell energy on Sunday 18 Oct at 2am CEST",
"Secondary Swell energy on Sunday 18 Oct at 2am CEST",
"Wind Wave energy on Sunday 18 Oct at 2am CEST",
"Max Wave energy on Sunday 18 Oct at 2am CEST",
"Cloud Cover on Sunday 18 Oct at 2am CEST",
"Surface Temperature on Sunday 18 Oct at 2am CEST",
"Surface Wind on Sunday 18 Oct at 2am CEST",
"Precipitation for 3 hrs ending Sunday 18 Oct at 2am CEST",
"Freezing level contours Sunday 18 Oct at 8am",
"Sea Level Pressure in Millibars Sunday 18 Oct at 8am",
"Lines show pressure and arrows show wind direction Sunday 18 Oct at 8am",
"FREEZING LEVEL CONTOURED (RED) IN METRES Sunday 18 Oct at 8am",
"FREEZING LEVEL CONTOURED (RED) IN FEET Sunday 18 Oct at 8am",
"Significant Wave Height in metres on Sunday 18 Oct at 8am CEST",
"Significant Wave Height in feet on Sunday 18 Oct at 8am CEST",
"Peak wave period on Sunday 18 Oct at 8am CEST",
"Primary Swell energy on Sunday 18 Oct at 8am CEST",
"Secondary Swell energy on Sunday 18 Oct at 8am CEST",
"Wind Wave energy on Sunday 18 Oct at 8am CEST",
"Max Wave energy on Sunday 18 Oct at 8am CEST",
"Cloud Cover on Sunday 18 Oct at 8am CEST",
"Surface Temperature on Sunday 18 Oct at 8am CEST",
"Surface Wind on Sunday 18 Oct at 8am CEST",
"Precipitation for 3 hrs ending Sunday 18 Oct at 8am CEST",
"Freezing level contours Sunday 18 Oct at 2pm",
"Sea Level Pressure in Millibars Sunday 18 Oct at 2pm",
"Lines show pressure and arrows show wind direction Sunday 18 Oct at 2pm",
"FREEZING LEVEL CONTOURED (RED) IN METRES Sunday 18 Oct at 2pm",
"FREEZING LEVEL CONTOURED (RED) IN FEET Sunday 18 Oct at 2pm",
"Significant Wave Height in metres on Sunday 18 Oct at 2pm CEST",
"Significant Wave Height in feet on Sunday 18 Oct at 2pm CEST",
"Peak wave period on Sunday 18 Oct at 2pm CEST",
"Primary Swell energy on Sunday 18 Oct at 2pm CEST",
"Secondary Swell energy on Sunday 18 Oct at 2pm CEST",
"Wind Wave energy on Sunday 18 Oct at 2pm CEST",
"Max Wave energy on Sunday 18 Oct at 2pm CEST",
"Cloud Cover on Sunday 18 Oct at 2pm CEST",
"Surface Temperature on Sunday 18 Oct at 2pm CEST",
"Surface Wind on Sunday 18 Oct at 2pm CEST",
"Precipitation for 3 hrs ending Sunday 18 Oct at 2pm CEST",
"Freezing level contours Sunday 18 Oct at 8pm",
"Sea Level Pressure in Millibars Sunday 18 Oct at 8pm",
"Lines show pressure and arrows show wind direction Sunday 18 Oct at 8pm",
"FREEZING LEVEL CONTOURED (RED) IN METRES Sunday 18 Oct at 8pm",
"FREEZING LEVEL CONTOURED (RED) IN FEET Sunday 18 Oct at 8pm",
"Significant Wave Height in metres on Sunday 18 Oct at 8pm CEST",
"Significant Wave Height in feet on Sunday 18 Oct at 8pm CEST",
"Peak wave period on Sunday 18 Oct at 8pm CEST",
"Primary Swell energy on Sunday 18 Oct at 8pm CEST",
"Secondary Swell energy on Sunday 18 Oct at 8pm CEST",
"Wind Wave energy on Sunday 18 Oct at 8pm CEST",
"Max Wave energy on Sunday 18 Oct at 8pm CEST",
"Cloud Cover on Sunday 18 Oct at 8pm CEST",
"Surface Temperature on Sunday 18 Oct at 8pm CEST",
"Surface Wind on Sunday 18 Oct at 8pm CEST",
"Precipitation for 3 hrs ending Sunday 18 Oct at 8pm CEST",
"Freezing level contours Monday 19 Oct at 2am",
"Sea Level Pressure in Millibars Monday 19 Oct at 2am",
"Lines show pressure and arrows show wind direction Monday 19 Oct at 2am",
"FREEZING LEVEL CONTOURED (RED) IN METRES Monday 19 Oct at 2am",
"FREEZING LEVEL CONTOURED (RED) IN FEET Monday 19 Oct at 2am",
"Significant Wave Height in metres on Monday 19 Oct at 2am CEST",
"Significant Wave Height in feet on Monday 19 Oct at 2am CEST",
"Peak wave period on Monday 19 Oct at 2am CEST",
"Primary Swell energy on Monday 19 Oct at 2am CEST",
"Secondary Swell energy on Monday 19 Oct at 2am CEST",
"Wind Wave energy on Monday 19 Oct at 2am CEST",
"Max Wave energy on Monday 19 Oct at 2am CEST",
"Cloud Cover on Monday 19 Oct at 2am CEST",
"Surface Temperature on Monday 19 Oct at 2am CEST",
"Surface Wind on Monday 19 Oct at 2am CEST",
"Precipitation for 3 hrs ending Monday 19 Oct at 2am CEST",
"Freezing level contours Monday 19 Oct at 8am",
"Sea Level Pressure in Millibars Monday 19 Oct at 8am",
"Lines show pressure and arrows show wind direction Monday 19 Oct at 8am",
"FREEZING LEVEL CONTOURED (RED) IN METRES Monday 19 Oct at 8am",
"FREEZING LEVEL CONTOURED (RED) IN FEET Monday 19 Oct at 8am",
"Significant Wave Height in metres on Monday 19 Oct at 8am CEST",
"Significant Wave Height in feet on Monday 19 Oct at 8am CEST",
"Peak wave period on Monday 19 Oct at 8am CEST",
"Primary Swell energy on Monday 19 Oct at 8am CEST",
"Secondary Swell energy on Monday 19 Oct at 8am CEST",
"Wind Wave energy on Monday 19 Oct at 8am CEST",
"Max Wave energy on Monday 19 Oct at 8am CEST",
"Cloud Cover on Monday 19 Oct at 8am CEST",
"Surface Temperature on Monday 19 Oct at 8am CEST",
"Surface Wind on Monday 19 Oct at 8am CEST",
"Precipitation for 3 hrs ending Monday 19 Oct at 8am CEST",
"Freezing level contours Monday 19 Oct at 2pm",
"Sea Level Pressure in Millibars Monday 19 Oct at 2pm",
"Lines show pressure and arrows show wind direction Monday 19 Oct at 2pm",
"FREEZING LEVEL CONTOURED (RED) IN METRES Monday 19 Oct at 2pm",
"FREEZING LEVEL CONTOURED (RED) IN FEET Monday 19 Oct at 2pm",
"Significant Wave Height in metres on Monday 19 Oct at 2pm CEST",
"Significant Wave Height in feet on Monday 19 Oct at 2pm CEST",
"Peak wave period on Monday 19 Oct at 2pm CEST",
"Primary Swell energy on Monday 19 Oct at 2pm CEST",
"Secondary Swell energy on Monday 19 Oct at 2pm CEST",
"Wind Wave energy on Monday 19 Oct at 2pm CEST",
"Max Wave energy on Monday 19 Oct at 2pm CEST",
"Cloud Cover on Monday 19 Oct at 2pm CEST",
"Surface Temperature on Monday 19 Oct at 2pm CEST",
"Surface Wind on Monday 19 Oct at 2pm CEST",
"Precipitation for 3 hrs ending Monday 19 Oct at 2pm CEST",
"Freezing level contours Monday 19 Oct at 8pm",
"Sea Level Pressure in Millibars Monday 19 Oct at 8pm",
"Lines show pressure and arrows show wind direction Monday 19 Oct at 8pm",
"FREEZING LEVEL CONTOURED (RED) IN METRES Monday 19 Oct at 8pm",
"FREEZING LEVEL CONTOURED (RED) IN FEET Monday 19 Oct at 8pm",
"Significant Wave Height in metres on Monday 19 Oct at 8pm CEST",
"Significant Wave Height in feet on Monday 19 Oct at 8pm CEST",
"Peak wave period on Monday 19 Oct at 8pm CEST",
"Primary Swell energy on Monday 19 Oct at 8pm CEST",
"Secondary Swell energy on Monday 19 Oct at 8pm CEST",
"Wind Wave energy on Monday 19 Oct at 8pm CEST",
"Max Wave energy on Monday 19 Oct at 8pm CEST",
"Cloud Cover on Monday 19 Oct at 8pm CEST",
"Surface Temperature on Monday 19 Oct at 8pm CEST",
"Surface Wind on Monday 19 Oct at 8pm CEST",
"Precipitation for 3 hrs ending Monday 19 Oct at 8pm CEST",
"Freezing level contours Tuesday 20 Oct at 2am",
"Sea Level Pressure in Millibars Tuesday 20 Oct at 2am",
"Lines show pressure and arrows show wind direction Tuesday 20 Oct at 2am",
"FREEZING LEVEL CONTOURED (RED) IN METRES Tuesday 20 Oct at 2am",
"FREEZING LEVEL CONTOURED (RED) IN FEET Tuesday 20 Oct at 2am",
"Significant Wave Height in metres on Tuesday 20 Oct at 2am CEST",
"Significant Wave Height in feet on Tuesday 20 Oct at 2am CEST",
"Peak wave period on Tuesday 20 Oct at 2am CEST",
"Primary Swell energy on Tuesday 20 Oct at 2am CEST",
"Secondary Swell energy on Tuesday 20 Oct at 2am CEST",
"Wind Wave energy on Tuesday 20 Oct at 2am CEST",
"Max Wave energy on Tuesday 20 Oct at 2am CEST",
"Cloud Cover on Tuesday 20 Oct at 2am CEST",
"Surface Temperature on Tuesday 20 Oct at 2am CEST",
"Surface Wind on Tuesday 20 Oct at 2am CEST",
"Precipitation for 3 hrs ending Tuesday 20 Oct at 2am CEST",
"Freezing level contours Tuesday 20 Oct at 8am",
"Sea Level Pressure in Millibars Tuesday 20 Oct at 8am",
"Lines show pressure and arrows show wind direction Tuesday 20 Oct at 8am",
"FREEZING LEVEL CONTOURED (RED) IN METRES Tuesday 20 Oct at 8am",
"FREEZING LEVEL CONTOURED (RED) IN FEET Tuesday 20 Oct at 8am",
"Cloud Cover on Tuesday 20 Oct at 8am CEST",
"Surface Temperature on Tuesday 20 Oct at 8am CEST",
"Surface Wind on Tuesday 20 Oct at 8am CEST",
"Precipitation for 3 hrs ending Tuesday 20 Oct at 8am CEST",
"Freezing level contours Tuesday 20 Oct at 2pm",
"Sea Level Pressure in Millibars Tuesday 20 Oct at 2pm",
"Lines show pressure and arrows show wind direction Tuesday 20 Oct at 2pm",
"FREEZING LEVEL CONTOURED (RED) IN METRES Tuesday 20 Oct at 2pm",
"FREEZING LEVEL CONTOURED (RED) IN FEET Tuesday 20 Oct at 2pm",
"Cloud Cover on Tuesday 20 Oct at 2pm CEST",
"Surface Temperature on Tuesday 20 Oct at 2pm CEST",
"Surface Wind on Tuesday 20 Oct at 2pm CEST",
"Precipitation for 3 hrs ending Tuesday 20 Oct at 2pm CEST",
"Freezing level contours Tuesday 20 Oct at 8pm",
"Sea Level Pressure in Millibars Tuesday 20 Oct at 8pm",
"Lines show pressure and arrows show wind direction Tuesday 20 Oct at 8pm",
"FREEZING LEVEL CONTOURED (RED) IN METRES Tuesday 20 Oct at 8pm",
"FREEZING LEVEL CONTOURED (RED) IN FEET Tuesday 20 Oct at 8pm",
"Cloud Cover on Tuesday 20 Oct at 8pm CEST",
"Surface Temperature on Tuesday 20 Oct at 8pm CEST",
"Surface Wind on Tuesday 20 Oct at 8pm CEST",
"Precipitation for 3 hrs ending Tuesday 20 Oct at 8pm CEST",
"Freezing level contours Wednesday 21 Oct at 2am",
"Sea Level Pressure in Millibars Wednesday 21 Oct at 2am",
"Lines show pressure and arrows show wind direction Wednesday 21 Oct at 2am",
"FREEZING LEVEL CONTOURED (RED) IN METRES Wednesday 21 Oct at 2am",
"FREEZING LEVEL CONTOURED (RED) IN FEET Wednesday 21 Oct at 2am",
"Cloud Cover on Wednesday 21 Oct at 2am CEST",
"Surface Temperature on Wednesday 21 Oct at 2am CEST",
"Surface Wind on Wednesday 21 Oct at 2am CEST",
"Precipitation for 3 hrs ending Wednesday 21 Oct at 2am CEST",
"Freezing level contours Wednesday 21 Oct at 8am",
"Sea Level Pressure in Millibars Wednesday 21 Oct at 8am",
"Lines show pressure and arrows show wind direction Wednesday 21 Oct at 8am",
"FREEZING LEVEL CONTOURED (RED) IN METRES Wednesday 21 Oct at 8am",
"FREEZING LEVEL CONTOURED (RED) IN FEET Wednesday 21 Oct at 8am",
"Cloud Cover on Wednesday 21 Oct at 8am CEST",
"Surface Temperature on Wednesday 21 Oct at 8am CEST",
"Surface Wind on Wednesday 21 Oct at 8am CEST",
"Precipitation for 3 hrs ending Wednesday 21 Oct at 8am CEST",
"Freezing level contours Wednesday 21 Oct at 2pm",
"Sea Level Pressure in Millibars Wednesday 21 Oct at 2pm",
"Lines show pressure and arrows show wind direction Wednesday 21 Oct at 2pm",
"FREEZING LEVEL CONTOURED (RED) IN METRES Wednesday 21 Oct at 2pm",
"FREEZING LEVEL CONTOURED (RED) IN FEET Wednesday 21 Oct at 2pm",
"Cloud Cover on Wednesday 21 Oct at 2pm CEST",
"Surface Temperature on Wednesday 21 Oct at 2pm CEST",
"Surface Wind on Wednesday 21 Oct at 2pm CEST",
"Precipitation for 3 hrs ending Wednesday 21 Oct at 2pm CEST",
"Freezing level contours Wednesday 21 Oct at 8pm",
"Sea Level Pressure in Millibars Wednesday 21 Oct at 8pm",
"Lines show pressure and arrows show wind direction Wednesday 21 Oct at 8pm",
"FREEZING LEVEL CONTOURED (RED) IN METRES Wednesday 21 Oct at 8pm",
"FREEZING LEVEL CONTOURED (RED) IN FEET Wednesday 21 Oct at 8pm",
"Cloud Cover on Wednesday 21 Oct at 8pm CEST",
"Surface Temperature on Wednesday 21 Oct at 8pm CEST",
"Surface Wind on Wednesday 21 Oct at 8pm CEST",
"Precipitation for 3 hrs ending Wednesday 21 Oct at 8pm CEST",
"Freezing level contours Thursday 22 Oct at 2am",
"Sea Level Pressure in Millibars Thursday 22 Oct at 2am",
"Lines show pressure and arrows show wind direction Thursday 22 Oct at 2am",
"FREEZING LEVEL CONTOURED (RED) IN METRES Thursday 22 Oct at 2am",
"FREEZING LEVEL CONTOURED (RED) IN FEET Thursday 22 Oct at 2am",
"Cloud Cover on Thursday 22 Oct at 2am CEST",
"Surface Temperature on Thursday 22 Oct at 2am CEST",
"Surface Wind on Thursday 22 Oct at 2am CEST",
"Precipitation for 3 hrs ending Thursday 22 Oct at 2am CEST",
"Freezing level contours Thursday 22 Oct at 8am",
"Sea Level Pressure in Millibars Thursday 22 Oct at 8am",
"Lines show pressure and arrows show wind direction Thursday 22 Oct at 8am",
"FREEZING LEVEL CONTOURED (RED) IN METRES Thursday 22 Oct at 8am",
"FREEZING LEVEL CONTOURED (RED) IN FEET Thursday 22 Oct at 8am",
"Cloud Cover on Thursday 22 Oct at 8am CEST",
"Surface Temperature on Thursday 22 Oct at 8am CEST",
"Surface Wind on Thursday 22 Oct at 8am CEST",
"Precipitation for 3 hrs ending Thursday 22 Oct at 8am CEST",
"Freezing level contours Thursday 22 Oct at 2pm",
"Sea Level Pressure in Millibars Thursday 22 Oct at 2pm",
"Lines show pressure and arrows show wind direction Thursday 22 Oct at 2pm",
"FREEZING LEVEL CONTOURED (RED) IN METRES Thursday 22 Oct at 2pm",
"FREEZING LEVEL CONTOURED (RED) IN FEET Thursday 22 Oct at 2pm",
"Cloud Cover on Thursday 22 Oct at 2pm CEST",
"Surface Temperature on Thursday 22 Oct at 2pm CEST",
"Surface Wind on Thursday 22 Oct at 2pm CEST",
"Precipitation for 3 hrs ending Thursday 22 Oct at 2pm CEST",
"Freezing level contours Thursday 22 Oct at 8pm",
"Sea Level Pressure in Millibars Thursday 22 Oct at 8pm",
"Lines show pressure and arrows show wind direction Thursday 22 Oct at 8pm",
"FREEZING LEVEL CONTOURED (RED) IN METRES Thursday 22 Oct at 8pm",
"FREEZING LEVEL CONTOURED (RED) IN FEET Thursday 22 Oct at 8pm",
"Cloud Cover on Thursday 22 Oct at 8pm CEST",
"Surface Temperature on Thursday 22 Oct at 8pm CEST",
"Surface Wind on Thursday 22 Oct at 8pm CEST",
"Precipitation for 3 hrs ending Thursday 22 Oct at 8pm CEST",
"Freezing level contours Friday 23 Oct at 2am",
"Sea Level Pressure in Millibars Friday 23 Oct at 2am",
"Lines show pressure and arrows show wind direction Friday 23 Oct at 2am",
"FREEZING LEVEL CONTOURED (RED) IN METRES Friday 23 Oct at 2am",
"FREEZING LEVEL CONTOURED (RED) IN FEET Friday 23 Oct at 2am",
"Cloud Cover on Friday 23 Oct at 2am CEST",
"Surface Temperature on Friday 23 Oct at 2am CEST",
"Surface Wind on Friday 23 Oct at 2am CEST",
"Precipitation for 3 hrs ending Friday 23 Oct at 2am CEST",
"Freezing level contours Friday 23 Oct at 8am",
"Sea Level Pressure in Millibars Friday 23 Oct at 8am",
"Lines show pressure and arrows show wind direction Friday 23 Oct at 8am",
"FREEZING LEVEL CONTOURED (RED) IN METRES Friday 23 Oct at 8am",
"FREEZING LEVEL CONTOURED (RED) IN FEET Friday 23 Oct at 8am",
"Cloud Cover on Friday 23 Oct at 8am CEST",
"Surface Temperature on Friday 23 Oct at 8am CEST",
"Surface Wind on Friday 23 Oct at 8am CEST",
"Precipitation for 3 hrs ending Friday 23 Oct at 8am CEST",
"Freezing level contours Friday 23 Oct at 2pm",
"Sea Level Pressure in Millibars Friday 23 Oct at 2pm",
"Lines show pressure and arrows show wind direction Friday 23 Oct at 2pm",
"FREEZING LEVEL CONTOURED (RED) IN METRES Friday 23 Oct at 2pm",
"FREEZING LEVEL CONTOURED (RED) IN FEET Friday 23 Oct at 2pm",
"Cloud Cover on Friday 23 Oct at 2pm CEST",
"Surface Temperature on Friday 23 Oct at 2pm CEST",
"Surface Wind on Friday 23 Oct at 2pm CEST",
"Precipitation for 3 hrs ending Friday 23 Oct at 2pm CEST",
"Freezing level contours Friday 23 Oct at 8pm",
"Sea Level Pressure in Millibars Friday 23 Oct at 8pm",
"Lines show pressure and arrows show wind direction Friday 23 Oct at 8pm",
"FREEZING LEVEL CONTOURED (RED) IN METRES Friday 23 Oct at 8pm",
"FREEZING LEVEL CONTOURED (RED) IN FEET Friday 23 Oct at 8pm",
"Cloud Cover on Friday 23 Oct at 8pm CEST",
"Surface Temperature on Friday 23 Oct at 8pm CEST",
"Surface Wind on Friday 23 Oct at 8pm CEST",
"Precipitation for 3 hrs ending Friday 23 Oct at 8pm CEST",
"Freezing level contours Saturday 24 Oct at 2am",
"Sea Level Pressure in Millibars Saturday 24 Oct at 2am",
"Lines show pressure and arrows show wind direction Saturday 24 Oct at 2am",
"FREEZING LEVEL CONTOURED (RED) IN METRES Saturday 24 Oct at 2am",
"FREEZING LEVEL CONTOURED (RED) IN FEET Saturday 24 Oct at 2am",
"Cloud Cover on Saturday 24 Oct at 2am CEST",
"Surface Temperature on Saturday 24 Oct at 2am CEST",
"Surface Wind on Saturday 24 Oct at 2am CEST",
"Precipitation for 3 hrs ending Saturday 24 Oct at 2am CEST",
"Freezing level contours Saturday 24 Oct at 8am",
"Sea Level Pressure in Millibars Saturday 24 Oct at 8am",
"Lines show pressure and arrows show wind direction Saturday 24 Oct at 8am",
"FREEZING LEVEL CONTOURED (RED) IN METRES Saturday 24 Oct at 8am",
"FREEZING LEVEL CONTOURED (RED) IN FEET Saturday 24 Oct at 8am",
"Cloud Cover on Saturday 24 Oct at 8am CEST",
"Surface Temperature on Saturday 24 Oct at 8am CEST",
"Surface Wind on Saturday 24 Oct at 8am CEST",
"Precipitation for 3 hrs ending Saturday 24 Oct at 8am CEST",
"Freezing level contours Saturday 24 Oct at 2pm",
"Sea Level Pressure in Millibars Saturday 24 Oct at 2pm",
"Lines show pressure and arrows show wind direction Saturday 24 Oct at 2pm",
"FREEZING LEVEL CONTOURED (RED) IN METRES Saturday 24 Oct at 2pm",
"FREEZING LEVEL CONTOURED (RED) IN FEET Saturday 24 Oct at 2pm",
"Cloud Cover on Saturday 24 Oct at 2pm CEST",
"Surface Temperature on Saturday 24 Oct at 2pm CEST",
"Surface Wind on Saturday 24 Oct at 2pm CEST",
"Precipitation for 3 hrs ending Saturday 24 Oct at 2pm CEST",
"Freezing level contours Saturday 24 Oct at 8pm",
"Sea Level Pressure in Millibars Saturday 24 Oct at 8pm",
"Lines show pressure and arrows show wind direction Saturday 24 Oct at 8pm",
"FREEZING LEVEL CONTOURED (RED) IN METRES Saturday 24 Oct at 8pm",
"FREEZING LEVEL CONTOURED (RED) IN FEET Saturday 24 Oct at 8pm",
"Cloud Cover on Saturday 24 Oct at 8pm CEST",
"Surface Temperature on Saturday 24 Oct at 8pm CEST",
"Surface Wind on Saturday 24 Oct at 8pm CEST",
"Precipitation for 3 hrs ending Saturday 24 Oct at 8pm CEST",
"Freezing level contours Sunday 25 Oct at 2am",
"Sea Level Pressure in Millibars Sunday 25 Oct at 2am",
"Lines show pressure and arrows show wind direction Sunday 25 Oct at 2am",
"FREEZING LEVEL CONTOURED (RED) IN METRES Sunday 25 Oct at 2am",
"FREEZING LEVEL CONTOURED (RED) IN FEET Sunday 25 Oct at 2am",
"Cloud Cover on Sunday 25 Oct at 2am CEST",
"Surface Temperature on Sunday 25 Oct at 2am CEST",
"Surface Wind on Sunday 25 Oct at 2am CEST",
"Precipitation for 3 hrs ending Sunday 25 Oct at 2am CEST"
]
